import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
     header:{
         paddingHorizontal:20,
         paddingVertical:10,
         flexDirection:'row',
         justifyContent:'space-between'
     },
     imgContainer:{
         flex:1,
         marginTop:20,
         justifyContent:'center',
         alignItems:'center'
     },
     detailsContainer:{
         flex:0.6,
         backgroundColor:'#fdf0ee',
         marginHorizontal:7,
         marginBottom:7,
         borderRadius:20,
         marginTop:30,
         padding:10,
         paddingLeft:20
     },
     detailName:{
         fontSize:23,
         fontWeight:'bold',
         marginBottom:10
     },
     detailInfo:{
         fontSize:16,
         marginBottom:10
     },
     detailHeart:{
         position:'absolute',
         top:25,
         right:20,
         color:'#F67280'
     },
     detailNormal:{
         fontSize:16,
         fontWeight:'600',
         marginBottom:5
     },
     detailColor:{
         flexDirection:'row',
         justifyContent:'space-evenly'
     },
     detailSize:{
         fontSize:17,
         fontWeight:'600',
         marginTop:5,
         borderWidth:1,
         borderColor:'black',
         borderRadius:15,
         paddingHorizontal:5,
         paddingVertical:4
     },
     detailBottom:{
         flexDirection:'row',
         justifyContent:'space-between',
         alignItems:'center',
         marginTop:15
     },
     btn:{
         fontSize:19,
         paddingHorizontal:50,
         paddingVertical:10,
         borderWidth:1,
         borderRadius:2,
         borderColor:'#ce8f86',
         backgroundColor:'#ce8f86',
         color:'white'
     }
})

export default styles